package com.dinhlam.sharebox.common

object AppExtras {
    const val EXTRA_SHARE_ID = "extra-share-id"
    const val EXTRA_PASSCODE = "extra-passcode"
    const val EXTRA_BOOKMARK_COLLECTION = "extra-bookmark-collection"
    const val EXTRA_BOOKMARK_COLLECTION_ID = "extra-bookmark-collection-id"
    const val EXTRA_PASSCODE_DESCRIPTION = "extra-passcode-description"
    const val EXTRA_IMAGE_URIS = "extra-image-uris"
    const val EXTRA_CHOICE_ITEMS = "extra-choice-items"
    const val EXTRA_SIGN_IN_FOR_RESULT = "extra-sign-in-for-result"
    const val EXTRA_BOX_ID = "extra-box-id"
    const val EXTRA_BOX_NAME = "extra-box-name"
    const val EXTRA_BOX_DETAIL = "extra-box-detail"
    const val EXTRA_URL = "extra-url"
    const val EXTRA_URLS = "extra-urls"
    const val EXTRA_DOWNLOAD_VIDEOS = "extra-download-videos"
    const val EXTRA_DOWNLOAD_AUDIOS = "extra-download-audios"
    const val EXTRA_DOWNLOAD_IMAGES = "extra-download-images"
    const val EXTRA_ID = "extra-id"
    const val EXTRA_TITLE = "extra-title"
    const val EXTRA_NOTIFICATION_ID = "extra-notification-id"
    const val EXTRA_BOOLEAN = "extra-boolean"
    const val EXTRA_MIMETYPE = "extra-mimetype"
    const val EXTRA_NAME = "extra-name"
    const val EXTRA_DATA = "extra-data"
    const val EXTRA_POSITION = "extra-data"
}
